# Generated by Django 4.2.20 on 2025-04-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventanalytics',
            name='age_group_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eventanalytics',
            name='cancellation_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='eventanalytics',
            name='daily_registrations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eventanalytics',
            name='location_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eventanalytics',
            name='total_cancellations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventanalytics',
            name='waitlist_conversions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventanalytics',
            name='waitlist_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventanalytics',
            name='weekly_registrations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
